---
# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
- name: install docker ce v{{ docker_ce_version }}
  environment:
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
  script: "get-docker.sh {{ docker_ce_version }}"
  args:
    creates: /usr/bin/docker

- name: pin docker ce v{{ docker_ce_version }}
  template:
    src: docker.j2
    dest: /etc/apt/preferences.d/docker

- name: configure daemon
  blockinfile:
    path: /etc/docker/daemon.json
    create: true
    block: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
  notify: restart_docker

- name: create systemd service
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory 
  notify: restart_docker
